spring.application.name=e-commerce-application

# ===============================
# DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/e_commerce_db_1
spring.datasource.username=root
spring.datasource.password=Root@123

# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Optional but recommended
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# SERVER CONFIG (optional)
# ===============================
server.port=8080
